### ISSUE TITLE
Support UUID param on PXE endpoint

### ISSUE THREAD

**Issue by bastelfreak** [virtapi/marmoset#61]
we would like to pass an additional param to the pxe endpoint, a UUID. This will later be used from the installimage to interact with APIs. You can currently pass it, but it gets ignored:

```
root@dhcp01 ~ # curl -u admin:secret --data 'ip_address=10.30.7.41&label=archrescue&uuid=345455645645456' http://dhcp01de:8080/v1/pxe
{
    "ip_address": "10.30.7.41",
    "label": "archrescue",
    "password": "Qs4o5XwHVYcn_8AY",
    "script": null
}
root@dhcp01 ~ # cat /srv/tftp/pxelinux.cfg/0A1E0729 
INCLUDE pxelinux.cfg/default
DEFAULT instantboot
PROMPT 0
TIMEOUT 1
LABEL instantboot
    KERNEL cmd.c32
    APPEND archrescue HASH=$6$TzG382c1PO9ogCT1$pO9rMFtWSCoxv9xRrBTsmsiunr5HJcufp8nSWHMrquetZ5g29FJ4sqnJbo7rTmaUKh7b5TA9wKDIlII5.Y3o21
root@dhcp01 ~ #
```

**Comment by bastelfreak** [comment]
because I'm old and forgetting stufff: we need this in the pxe endpoint, not installimage. this allows us to implement a keep-alive script in the livesystem which we can use if a booted system still does _something_. This will be very funny if we ever run root on NFS setups and the NFS dies for a short (or longer ime)...

**Comment by bastelfreak** [comment]
How do we want to deal with malformend UUIDs that we get? recreate a new one or don't accept the data at all and return a bad http status code?

**Comment by pbyatshon** [comment]
tgo

**Comment by bastelfreak** [comment]
Another funny thing, do we care about duplicate UUIDs?

**Comment by pbyatshon** [comment]
I think we should create a UUID for every PXE config, that would help us to track every installation status. If none supplied, create a UUID4, if invalid UUID create one as well.

Concerning duplicate UUIDs, thats a good question, depends on further intended use. Generating a duplicate UUID is highly unlikely, such situation might only occur when testing with fixed values. With a database backend we could easily lookup for dupes, otherwise we would have to scan each configuration file, which wouldn't be so nice. If we wanna care for dupes, the POST might result in a 409.

**Comment by bastelfreak** [comment]
I would like to keep the plain files, I think we can ignore the case of two duplicate UUIDs. What about returning 409 on a malformend UUID that we got?

**Comment by sebastianrakel** [comment]
We could use the uuid as filename, so you don't have to scan every file

**Comment by bastelfreak** [comment]
Sounds great

**Comment by bastelfreak** [comment]
implemented

**Comment by sebastianrakel** [comment]
oeh... this is not implemented...

**Comment by bastelfreak** [comment]
okay, UUID-as-filename is missing, but in general it is working and tested \o/

**Comment by pbyatshon** [comment]
furthermore we still need to define, how we want to handle malformed uuid, missing uuid and duplicated uuid. 

I just reconsidered searching the PXE files for a duplicate uuid,  that shouldn't be a real problem. For 10k PXE files it took 0.185s (sys 0.080s) and for 100k files it took 1.422s (sys 0.716s). 

Considering that also in a very large environment we won't get such a high POST rate that this might become a problem, i think we can leave it as is and search the PXE configurations for duplicates. Nevertheless we won't have a history, so that in general the API user should be responsible that the UUIDs used are really unique, if he want's to be able to track the installations correctly.

**Comment by bastelfreak** [comment]
we can't use the UUID as a filename for the pxeconfig because pxelinux searches for the IP or MAC of the client as filename.

**Comment by bastelfreak** [comment]
After a bit of reconsideration, this is now defined as properly implemented.
